name: Sync Image to Aliyun

run-name: 同步mockserver镜像
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: mockserver-latest

    steps:
    - name: Git pull
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2.9.1

    - name: Login to Docker Hub
      uses: docker/login-action@v2.2.0
      with:
        registry: registry.cn-shanghai.aliyuncs.com
        username: 1069355234@qq.com
        password: Monday@3721
        logout: false

    - name: Use Skopeo Tools Sync Image to Docker Hub
      run: |
        #!/usr/bin/env bash
        skopeo copy docker://docker.io/homebrew/jamesdbloom/mockserver:latest docker://registry.cn-shanghai.aliyuncs.com/zdf321/jamesdbloom-mockserver:latest
